{
 "title": "Tedee",
 "description": "Tedee lock ",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "deviceType",
    "label": "deviceType",
    "query": {
     "query": "label_values(tedee_lock_status_changed_total{deviceType=\"Lock Pro\"},deviceType)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "$deviceType battery level",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tedee_device_battery_level_ratio",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$deviceType battery level changed",
   "type": "barchart",
   "description": "Occures when Tedee Lock battery level changes",
   "gridPos": { "h": 5, "w": 7, "x": 5, "y": 0 },
   "targets": [
    {
     "expr": "tedee_device_battery_level_ratio{deviceType=\"$deviceType\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$deviceType status changed",
   "type": "timeseries",
   "description": "Occures when Tedee Lock status has changed",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(increase(tedee_lock_status_changed_total[$__rate_interval])) by (state) != 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Backend connection changed",
   "type": "timeseries",
   "description": "Occures when Tedee Bridge gets or looses connection to Tedee Cloud.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "sum(rate(tedee_backend_connection_changed_total[$__rate_interval])) by (state)",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "$deviceType connection changed",
   "type": "timeseries",
   "description": "Occures when Tedee Lock gets or looses connection to the Bridge.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "targets": [
    {
     "expr": "sum(rate(tedee_device_connection_changed_total[$__rate_interval])) by (state)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}